In [14]:
import numpy as np

#Print the numpy version and the configuration

# print(np.__version__)
# print() #newline
# print(np.show_config())

#Initialise a vector that contains numbers from 1 to 20 and reverse it vector (first element becomes last).

numlist=[x for x in range(1,21)]
numvector=np.array(numlist) #creating vector
numvectorREV=np.flip(numvector) #reversing vector

#Create a 3x3 array with random values and find the minimum and maximum value.
rndmatrix=np.random.randint(low=0,high=999,size=(3,3))  #Create 3x3 matrix with random numbers from 0 to 998
rndmatrixMAX=np.max(rndmatrix) #finding max element
rndmatrixMIN=np.min(rndmatrix) #finding min element
print(rndmatrixMAX,rndmatrixMIN)
print()

#Consider a (5,5,8) shape array, what is the index (x,y,z) of the 100th element?
matrix3D=np.arange(0,5*5*8).reshape(5,5,8)
index=0
for x in range(0,5):
    for y in range(0,5):
        for z in range(0,8):
            index+=1
            if index==100:
                print(x,y,z)
                break
print()
#How to find common values between two arrays? Demonstrate.

arr1=np.arange(0,100)
arr2=np.arange(90,200)

common=np.intersect1d(arr1,arr2)

print(common)
print()
#Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

coordmatrix=np.random.uniform(0,10,size=(10,2))
print(coordmatrix)
for coord in coordmatrix:
    dist=(((coord[0])**2)+((coord[1])**2))
    dist=dist**0.5
    angle_radians = np.arctan2(coord[1],coord[0])
    coord[0]=dist
    coord[1]=np.degrees(angle_radians)
print()

print(coordmatrix)

print()
#Demonstrate printing all the values of an array.
printarray=np.arange(0,50)
for val in printarray:
    print(val, end=' ',)
print()

#How to convert a float (32 bits) array into an integer (32 bits) in place? Demonstrate using an example. [Use NumPy Datatypes]
floatarray=(np.random.uniform(0,20,size=10)).astype(np.float32) #create float32 array with random float numbers

intarray=np.rint(floatarray).astype(np.int32) #round each float to nearest int
print(floatarray)
print(floatarray.dtype)
print()
print(intarray)
print(intarray.dtype)
print()

959 73

2 2 3

[90 91 92 93 94 95 96 97 98 99]

[[4.77868079 3.19499862]
 [4.79838233 1.26473237]
 [9.52393156 3.9381958 ]
 [9.20060629 5.80703981]
 [2.61545635 9.89880708]
 [3.06670831 1.83322421]
 [2.84847629 6.65382727]
 [2.06230002 1.15157074]
 [9.46728726 7.01338738]
 [9.49229437 4.91177897]]

[[ 5.74837423 33.76646066]
 [ 4.96225967 14.76589711]
 [10.30604961 22.46535181]
 [10.87992957 32.25841566]
 [10.23850544 75.19957417]
 [ 3.57287152 30.87023874]
 [ 7.23790263 66.8244306 ]
 [ 2.3620323  29.17861837]
 [11.78206818 36.53112964]
 [10.68780731 27.35926345]]

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 
[15.579727  19.45627    4.7661533  6.8153114 10.586701  11.285128
 10.031433  19.738508  16.687897  10.543877 ]

[16 19  5  7 11 11 10 20 17 11]

