In [5]:
import numpy as np

#Print the numpy version and the configuration

print(np.__version__)
print() #newline
print(np.show_config())
print()

#Initialise a vector that contains numbers from 1 to 20 and reverse it vector (first element becomes last).

numlist=[x for x in range(1,21)]
numvector=np.array(numlist) #creating vector
print(numvector)
numvectorREV=np.flip(numvector) #reversing vector
print(numvectorREV)
print()

#Create a 3x3 array with random values and find the minimum and maximum value.
rndmatrix=np.random.randint(low=0,high=999,size=(3,3))  #Create 3x3 matrix with random numbers from 0 to 998
rndmatrixMAX=np.max(rndmatrix) #finding max element
rndmatrixMIN=np.min(rndmatrix) #finding min element
print(rndmatrixMAX,rndmatrixMIN)
print()

#Consider a (5,5,8) shape array, what is the index (x,y,z) of the 100th element?
matrix3D=np.arange(0,5*5*8).reshape(5,5,8)
index=0
for x in range(0,5):
    for y in range(0,5):
        for z in range(0,8):
            index+=1
            if index==100:
                print(x,y,z)
                break
print()
#How to find common values between two arrays? Demonstrate.

arr1=np.arange(0,100)
arr2=np.arange(90,200)

common=np.intersect1d(arr1,arr2)

print(common)
print()
#Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

coordmatrix=np.random.uniform(0,10,size=(10,2))
print(coordmatrix)
for coord in coordmatrix:
    dist=(((coord[0])**2)+((coord[1])**2))
    dist=dist**0.5
    angle_radians = np.arctan2(coord[1],coord[0])
    coord[0]=dist
    coord[1]=np.degrees(angle_radians)

print()

print(coordmatrix)

print()
#Demonstrate printing all the values of an array.
printarray=np.arange(0,50)
for val in printarray:
    print(val, end=' ',)

print()
print()
#How to convert a float (32 bits) array into an integer (32 bits) in place? Demonstrate using an example. [Use NumPy Datatypes]
floatarray=(np.random.uniform(0,20,size=10)).astype(np.float32) #create float32 array with random float numbers

intarray=np.rint(floatarray).astype(np.int32) #round each float to nearest int
print(floatarray)
print(floatarray.dtype)
print()
print(intarray)
print(intarray.dtype)
print()

1.25.2


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]

836 152

2 2 3

[90 91 92 93 94 95 96 97 98 99]

[[3.33766012 2.07128202]
 [1.82661589 8.55810119]
 [9.57632458 2.78580048]
 [8.2744889  0.49585805]
 [0.48373215 7.08352593]
 [9.06981973 1.71368715]
 [0.82948023 3.34493508]
 [7.68023636 4.31825276]
 [4.20010746 5.51953382]
 [0.65013142 6.05165164]]

[[ 3.92812733 31.82287245]
 [ 8.75086405 77.951741  ]
 [ 9.97329819 16.21997636]
 [ 8.28933302  3.42941276]
 [ 7.10002369 86.09335144]
 [ 9.23029542 10.69955424]
 [ 3.44624841 76.07268547]
 [ 8.81097824 29.34709727]
 [ 6.93586017 52.73055979]
 [ 6.0864734  83.86820831]]

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

[11.52224   13.669657   7.8671665 11.045554  15.096187   5.1455135
 10.017995   4.550709  12.056734  17.258335 ]
float32

[12 14  8 11 15  5 10  5 12 1